import {seedMarker} from './dev-seed-core';

export interface SeedSpec {
  path: string;
  data: Record<string, unknown>;
  preserveUnmanaged?: boolean;
}

const address = (street: string, city: string, state: string, postalCode: string) => ({
  street,
  exteriorNumber: '100',
  city,
  state,
  postalCode,
  country: 'México',
});

const marked = (data: Record<string, unknown>) => ({...data, ...seedMarker});

export function buildDevSeed(adminId: string, operatorId: string): SeedSpec[] {
  const operatorIds = [operatorId];
  const specs: SeedSpec[] = [
    {
      path: 'clients/demo_client_dev',
      data: marked({
        name: 'Cliente de pruebas — DEV',
        legalName: 'Cliente de pruebas — DEV, S.A. de C.V.',
        rfc: 'XAXX010101000',
        contactName: 'Persona de pruebas DEV',
        email: 'cliente.dev@example.test',
        phone: '5500000099',
        addressFull: 'Dirección ficticia para pruebas DEV, Querétaro, México',
        postalCode: '76000',
        status: 'active',
        notes: 'Registro demostrativo exclusivo para Emulator Suite y Firebase DEV.',
        operatorIds,
      }),
    },
    {
      path: 'clients/demo_client_001',
      data: marked({
        name: 'Fríos del Centro Demo',
        legalName: 'Fríos del Centro Demo, S.A. de C.V.',
        rfc: 'XAXX010101000',
        contactName: 'Contacto Ficticio Uno',
        email: 'contacto1@example.test',
        phone: '5500000001',
        status: 'active',
        notes: 'Cliente ficticio para demostración DEV.',
        operatorIds,
      }),
    },
    {
      path: 'clients/demo_client_002',
      data: marked({
        name: 'Procesadora del Bajío Demo',
        legalName: 'Procesadora del Bajío Demo, S.A. de C.V.',
        rfc: 'XAXX010101000',
        contactName: 'Contacto Ficticio Dos',
        email: 'contacto2@example.test',
        phone: '5500000002',
        status: 'active',
        notes: 'Cliente ficticio para demostración DEV.',
        operatorIds,
      }),
    },
    {
      path: 'clients/demo_client_003',
      data: marked({
        name: 'Logística Refrigerada Demo',
        legalName: 'Logística Refrigerada Demo, S.A. de C.V.',
        rfc: 'XAXX010101000',
        contactName: 'Contacto Ficticio Tres',
        email: 'contacto3@example.test',
        phone: '5500000003',
        status: 'active',
        notes: 'Cliente ficticio para demostración DEV.',
        operatorIds,
      }),
    },
    {
      path: 'sites/demo_site_001',
      data: marked({
        clientId: 'demo_client_001',
        name: 'Planta Querétaro Demo',
        type: 'plant',
        address: address('Avenida Industria Fría', 'Querétaro', 'Querétaro', '76000'),
        contactName: 'Contacto Planta Uno',
        contactPhone: '5500000101',
        status: 'active',
        operatorIds,
      }),
    },
    {
      path: 'sites/demo_site_002',
      data: marked({
        clientId: 'demo_client_002',
        name: 'Centro de Proceso León Demo',
        type: 'plant',
        address: address('Boulevard Procesos', 'León', 'Guanajuato', '37000'),
        contactName: 'Contacto Planta Dos',
        contactPhone: '5500000102',
        status: 'active',
        operatorIds,
      }),
    },
    {
      path: 'sites/demo_site_003',
      data: marked({
        clientId: 'demo_client_003',
        name: 'Almacén Monterrey Demo',
        type: 'warehouse',
        address: address('Parque Logístico Norte', 'Monterrey', 'Nuevo León', '64000'),
        contactName: 'Contacto Almacén',
        contactPhone: '5500000103',
        status: 'active',
        operatorIds,
      }),
    },
    {
      path: 'equipment/demo_equipment_001',
      data: marked({
        clientId: 'demo_client_001',
        siteId: 'demo_site_001',
        name: 'Compresor de proceso Demo',
        category: 'Compresor',
        brand: 'Bitzer',
        model: '4PES-15Y',
        serialNumber: 'DEMO-COMP-001',
        capacity: '15 HP',
        refrigerant: 'R-134a',
        technicalNotes: 'Equipo totalmente ficticio.',
        status: 'active',
        operatorIds,
      }),
    },
    {
      path: 'equipment/demo_equipment_002',
      data: marked({
        clientId: 'demo_client_001',
        siteId: 'demo_site_001',
        name: 'Evaporador cámara 1 Demo',
        category: 'Evaporador',
        brand: 'Marca Demo',
        model: 'EV-100',
        serialNumber: 'DEMO-EV-001',
        capacity: '10 TR',
        refrigerant: 'R-404A',
        technicalNotes: 'Equipo totalmente ficticio.',
        status: 'active',
        operatorIds,
      }),
    },
    {
      path: 'equipment/demo_equipment_003',
      data: marked({
        clientId: 'demo_client_002',
        siteId: 'demo_site_002',
        name: 'Chiller de proceso Demo',
        category: 'Chiller',
        brand: 'Marca Demo',
        model: 'CH-250',
        serialNumber: 'DEMO-CH-001',
        capacity: '25 TR',
        refrigerant: 'R-134a',
        technicalNotes: 'Equipo totalmente ficticio.',
        status: 'active',
        operatorIds,
      }),
    },
    {
      path: 'equipment/demo_equipment_004',
      data: marked({
        clientId: 'demo_client_002',
        siteId: 'demo_site_002',
        name: 'Condensador remoto Demo',
        category: 'Condensador',
        brand: 'Marca Demo',
        model: 'CD-500',
        serialNumber: 'DEMO-CD-001',
        capacity: '50 TR',
        refrigerant: 'R-410A',
        technicalNotes: 'Equipo totalmente ficticio.',
        status: 'active',
        operatorIds,
      }),
    },
    {
      path: 'equipment/demo_equipment_005',
      data: marked({
        clientId: 'demo_client_003',
        siteId: 'demo_site_003',
        name: 'Unidad condensadora Demo',
        category: 'Unidad condensadora',
        brand: 'Marca Demo',
        model: 'UC-300',
        serialNumber: 'DEMO-UC-001',
        capacity: '30 TR',
        refrigerant: 'R-404A',
        technicalNotes: 'Equipo totalmente ficticio.',
        status: 'active',
        operatorIds,
      }),
    },
  ];

  const catalogItems = [
    [
      'PROD-COMP-001',
      'product',
      'Compresor semihermético',
      'Compresor industrial de cuatro cilindros para refrigeración.',
      'Compresores',
      'pieza',
      'Bitzer',
      '4PES-15Y',
      482000,
      true,
    ],
    [
      'PROD-FILT-001',
      'product',
      'Filtro deshidratador',
      'Filtro deshidratador soldable de alta capacidad.',
      'Repuestos',
      'pieza',
      'Danfoss',
      'DML 164',
      7850,
      true,
    ],
    [
      'PROD-VALV-001',
      'product',
      'Válvula de expansión',
      'Válvula termostática para control de refrigerante.',
      'Válvulas',
      'pieza',
      'Danfoss',
      'TXV 2.5 TR',
      9630,
      true,
    ],
    [
      'PROD-CONT-001',
      'product',
      'Contactor industrial',
      'Contactor trifásico para tablero de control.',
      'Eléctrico',
      'pieza',
      'Schneider',
      'LC1D',
      2980,
      true,
    ],
    [
      'PROD-ACEI-001',
      'product',
      'Aceite para compresor',
      'Lubricante sintético compatible con refrigeración industrial.',
      'Consumibles',
      'litro',
      'Marca Demo',
      'POE-68',
      1450,
      true,
    ],
    [
      'PROD-SENS-001',
      'product',
      'Sensor de temperatura',
      'Sensor digital para monitoreo de cámara fría.',
      'Control',
      'pieza',
      'Marca Demo',
      'NTC-10K',
      890,
      true,
    ],
    [
      'SERV-MANT-001',
      'service',
      'Mantenimiento preventivo',
      'Servicio técnico de mantenimiento preventivo conforme a plan.',
      'Mantenimiento',
      'servicio',
      null,
      null,
      8500,
      true,
    ],
    [
      'SERV-DIAG-001',
      'service',
      'Diagnóstico especializado',
      'Diagnóstico integral y reporte técnico del sistema.',
      'Diagnóstico',
      'servicio',
      null,
      null,
      6500,
      true,
    ],
    [
      'SERV-PMAR-001',
      'service',
      'Puesta en marcha',
      'Arranque, parametrización y pruebas finales.',
      'Instalación',
      'servicio',
      null,
      null,
      9500,
      true,
    ],
    [
      'SERV-FUGA-001',
      'service',
      'Detección de fugas',
      'Inspección y detección electrónica de fugas.',
      'Diagnóstico',
      'servicio',
      null,
      null,
      4200,
      true,
    ],
    [
      'SERV-CARG-001',
      'service',
      'Carga de refrigerante',
      'Mano de obra para vacío y carga de refrigerante.',
      'Mantenimiento',
      'servicio',
      null,
      null,
      5800,
      true,
    ],
    [
      'SERV-CAPA-001',
      'service',
      'Capacitación operativa',
      'Capacitación al personal para operación segura del sistema.',
      'Capacitación',
      'sesión',
      null,
      null,
      7200,
      false,
    ],
  ] as const;
  for (const [
    code,
    type,
    name,
    description,
    category,
    unit,
    brand,
    model,
    basePrice,
    taxable,
  ] of catalogItems) {
    const searchTokens = [
      ...new Set(
        `${code} ${name} ${description} ${category} ${brand ?? ''} ${model ?? ''}`
          .normalize('NFD')
          .replace(/[\u0300-\u036f]/g, '')
          .toLowerCase()
          .split(/[^a-z0-9]+/)
          .filter(Boolean),
      ),
    ];
    specs.push({
      path: `catalogItems/${code}`,
      data: marked({
        code,
        type,
        name,
        description,
        category,
        unit,
        brand,
        model,
        basePrice,
        taxable,
        status: 'active',
        searchTokens,
      }),
    });
  }

  specs.push(
    {
      path: 'catalogs/demo_unit_service',
      data: marked({type: 'unit', name: 'Servicio', value: 'servicio', status: 'active'}),
    },
    {
      path: 'catalogs/demo_unit_piece',
      data: marked({type: 'unit', name: 'Pieza', value: 'pieza', status: 'active'}),
    },
    {
      path: 'catalogs/demo_priority_high',
      data: marked({type: 'priority', name: 'Alta', value: 'high', status: 'active'}),
    },
    {
      path: 'settings/companyProfile',
      preserveUnmanaged: true,
      data: marked({
        companyName: 'Enfriamatic DEV',
        rfc: '',
        address: 'México · Datos ficticios DEV',
        phone: '',
        email: '',
        legalText: 'Documento de demostración sin validez comercial.',
      }),
    },
    {
      path: 'settings/quoteDefaults',
      preserveUnmanaged: true,
      data: marked({
        taxRate: 0.16,
        validityDays: 15,
        currency: 'MXN',
        folioPrefix: 'COT',
        paymentMethod: 'Transferencia bancaria',
        advance: 'Según propuesta',
        estimatedTerm: 'Por confirmar',
        warranty: 'Según alcance',
        exclusions: 'Trabajos no descritos',
        observations: 'Datos ficticios DEV',
        devWatermark: 'DOCUMENTO DE PRUEBA - DEV',
      }),
    },
    {
      path: 'requests/demo_request_001',
      data: marked({
        clientId: 'demo_client_001',
        siteId: 'demo_site_001',
        equipmentId: 'demo_equipment_001',
        title: 'Diagnóstico de compresor Demo',
        description: 'Solicitud ficticia pendiente de asignación.',
        priority: 'high',
        status: 'pending',
        assignedTo: null,
        assignedAt: null,
        completedAt: null,
        correctionOfRequestId: null,
        correctionOfQuoteId: null,
      }),
    },
    {
      path: 'requests/demo_request_002',
      data: marked({
        clientId: 'demo_client_002',
        siteId: 'demo_site_002',
        equipmentId: 'demo_equipment_003',
        title: 'Mantenimiento de chiller Demo',
        description: 'Solicitud ficticia asignada al operador seleccionado.',
        priority: 'normal',
        status: 'assigned',
        assignedTo: operatorId,
        assignedAt: 'SERVER_TIMESTAMP',
        completedAt: null,
        correctionOfRequestId: null,
        correctionOfQuoteId: null,
      }),
    },
    {
      path: 'requests/demo_request_003',
      data: marked({
        clientId: 'demo_client_003',
        siteId: 'demo_site_003',
        equipmentId: 'demo_equipment_005',
        title: 'Revisión de unidad condensadora Demo',
        description: 'Solicitud ficticia actualmente en progreso.',
        priority: 'urgent',
        status: 'in_progress',
        assignedTo: operatorId,
        assignedAt: 'SERVER_TIMESTAMP',
        completedAt: null,
        correctionOfRequestId: null,
        correctionOfQuoteId: null,
      }),
    },
    {
      path: 'quotes/demo_quote_001',
      data: marked({
        folio: '',
        requestId: 'demo_request_003',
        assignedTo: operatorId,
        clientId: 'demo_client_003',
        siteId: 'demo_site_003',
        equipmentId: 'demo_equipment_005',
        status: 'draft',
        documentStatus: 'not_generated',
        currency: 'MXN',
        taxRate: 0.16,
        discountDisplayMode: 'detailed',
        subtotalOriginal: 490500,
        discountTotal: 0,
        subtotalFinal: 490500,
        taxTotal: 78480,
        grandTotal: 568980,
        notes: 'Borrador ficticio generado por semilla DEV.',
        validityDays: 15,
        validUntil: null,
        issuedAt: null,
        issuedBy: null,
        originalQuoteId: null,
        revisionNumber: 1,
        locked: false,
      }),
    },
    {
      path: 'quotes/demo_quote_001/items/demo_item_001',
      data: marked({
        position: 0,
        catalogItemId: 'PROD-COMP-001',
        catalogCode: 'PROD-COMP-001',
        catalogType: 'product',
        catalogSnapshot: {
          code: 'PROD-COMP-001',
          type: 'product',
          name: 'Compresor semihermético',
          description: 'Compresor industrial de cuatro cilindros para refrigeración.',
          category: 'Compresores',
          unit: 'pieza',
          brand: 'Bitzer',
          model: '4PES-15Y',
          basePrice: 482000,
          taxable: true,
        },
        quantity: 1,
        unit: 'pieza',
        equipmentOrService: 'Compresor semihermético',
        brand: 'Bitzer',
        model: '4PES-15Y',
        description: 'Compresor industrial de cuatro cilindros para refrigeración.',
        originalUnitPrice: 482000,
        discountType: 'none',
        discountValue: 0,
        discountAmount: 0,
        finalUnitPrice: 482000,
        lineSubtotal: 482000,
        taxable: true,
      }),
    },
    {
      path: 'quotes/demo_quote_001/items/demo_item_002',
      data: marked({
        position: 1,
        catalogItemId: 'SERV-MANT-001',
        catalogCode: 'SERV-MANT-001',
        catalogType: 'service',
        catalogSnapshot: {
          code: 'SERV-MANT-001',
          type: 'service',
          name: 'Mantenimiento preventivo',
          description: 'Servicio técnico de mantenimiento preventivo conforme a plan.',
          category: 'Mantenimiento',
          unit: 'servicio',
          brand: null,
          model: null,
          basePrice: 8500,
          taxable: true,
        },
        quantity: 1,
        unit: 'servicio',
        equipmentOrService: 'Mantenimiento preventivo',
        brand: '',
        model: '',
        description: 'Servicio técnico de mantenimiento preventivo conforme a plan.',
        originalUnitPrice: 8500,
        discountType: 'none',
        discountValue: 0,
        discountAmount: 0,
        finalUnitPrice: 8500,
        lineSubtotal: 8500,
        taxable: true,
      }),
    },
    {
      path: 'notifications/demo_notification_001',
      data: marked({
        userId: operatorId,
        type: 'request_assigned',
        title: 'Solicitud Demo asignada',
        message: 'Tienes una solicitud ficticia asignada para la demostración.',
        resourceType: 'request',
        resourceId: 'demo_request_002',
        read: false,
        readAt: null,
      }),
    },
    {
      path: 'notifications/demo_notification_002',
      data: marked({
        userId: adminId,
        type: 'dev_seed_ready',
        title: 'Demostración DEV preparada',
        message: 'Los datos ficticios del cierre funcional están disponibles.',
        resourceType: 'system',
        resourceId: 'functional-dev-v1',
        read: false,
        readAt: null,
      }),
    },
  );
  return specs;
}
